"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Sebastian Harasimiuk, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: sph974
"""


class Node:
    """
    A modified version of the Node class for linked lists (using proper class
    coding practices). Instead of a data instance variable, this node class has both
    a coefficient and an exponent instance variable, which is used to represent each
    term in a polynomial.
    """

    def __init__(self, coeff, exp, link=None):
        """
        Node Constructor for polynomial linked lists.

        Args:
        - coeff: The coefficient of the term.
        - exp: The exponent of the term.
        - link: The next node in the linked list.
        """
        self.coeff = coeff
        self.exp = exp
        self.next = link

    @property
    def coeff(self):
        """
        Getter method for the coefficient attribute.
        """
        return self.__coeff

    @coeff.setter
    def coeff(self, value):
        """
        Setter method for the coefficient attribute.
        """
        if value is None or isinstance(value, int):
            self.__coeff = value
        else:
            raise ValueError("Coefficient must be an integer or None.")

    @property
    def exp(self):
        """
        Getter method for the exponent attribute.
        """
        return self.__exp

    @exp.setter
    def exp(self, value):
        """
        Setter method for the exponent attribute.
        """
        if value is None or isinstance(value, int):
            self.__exp = value
        else:
            raise ValueError("Exponent must be an integer or None.")

    @property
    def next(self):
        """
        Getter method for the next attribute.
        """
        return self.__next

    @next.setter
    def next(self, value):
        """
        Setter method for the next attribute.
        """
        if value is None or isinstance(value, Node):
            self.__next = value
        else:
            raise ValueError("Next must be a Node instance or None.")

    def __str__(self):
        """
        String representation of each term in a polynomial linked list.
        """
        return f"({self.coeff}, {self.exp})"


class LinkedList:
    def __init__(self):
        # You are also welcome to use a sentinel/dummy node!
        # It is definitely recommended, which will we learn more
        # about in class on Monday 10/21. If you choose to use
        # a dummy node, you can comment out the self.head = None
        # and comment in the below line. We use None to make sure
        # if there is an error where you accidentally include the
        # dummy node in your calculation, it will throw an error.
        # self.dummy = Node(None, None)
        self.head = None

    # Insert the term with the coefficient coeff and exponent exp into the polynomial.
    # If a term with that exponent already exists, add the coefficients together.
    # You must keep the terms in descending order by exponent.
    def insert_term(self, coeff, exp):
        if coeff != 0:
            if self.head is None:
                self.head = Node(coeff, exp, None)
                return
            else:
                current = self.head
                previous = None
                while current is not None:
                    if exp > current.exp:
                        if current == self.head:
                            new_node = Node(coeff, exp, current)
                            self.head = new_node
                        else:
                            new_node = Node(coeff, exp, current)
                            previous.next = new_node
                        return
                    elif exp == current.exp:
                        current.coeff += coeff
                        if current.coeff == 0:
                            if current == self.head:
                                self.head = current.next
                            else:
                                previous.next = current.next
                        return
                    previous = current
                    current = current.next
                previous.next = Node(coeff, exp, None)
                return

    # Add a polynomial p to the polynomial and return the resulting polynomial as a new linked list.
    def add(self, p):
        new_list = LinkedList()

        if self.head is not None:
            current = self.head
            while current:
                new_list.insert_term(current.coeff, current.exp)
                current = current.next

        if p.head is not None:
            current = p.head
            while current:
                new_list.insert_term(current.coeff, current.exp)
                current = current.next

        return new_list

    # Multiply a polynomial p with the polynomial and return the product as a new linked list.
    def mult(self, p):
        new_list = LinkedList()
        current = self.head
        while current is not None:
            current_2 = p.head
            while current_2 is not None:
                new_list.insert_term(current.coeff * current_2.coeff, current.exp + current_2.exp)
                current_2 = current_2.next
            current = current.next
        return new_list

    # Return a string representation of the polynomial.
    def __str__(self):
        poly_list = []
        current = self.head
        while current is not None:
            poly_list.append(f"({current.coeff}, {current.exp})")
            current = current.next
        poly_str = " + ".join(poly_list)
        return poly_str


def main():
    # file_num = int(input("Choose a file number: "))
    # with open(f"test_{file_num}.in") as f:
    #     lines = f.readlines()
    text = input()
    lines = text.split("\n")

    # read data from stdin using input() and create polynomial p
    p = LinkedList()
    p_len = int(lines[0])
    for i in range(1, p_len + 1):
        term = lines[i].split()
        p.insert_term(int(term[0]), int(term[1]))

    # read data from stdin using input() and create polynomial q
    q = LinkedList()
    for i in range(p_len + 3, len(lines)):
        term = lines[i].split()
        q.insert_term(int(term[0]), int(term[1]))

    # get sum of p and q as a new linked list and print sum
    p_q_sum = p.add(q)
    print(p_q_sum)

    # get product of p and q as a new linked list and print product
    p_q_product = p.mult(q)
    print(p_q_product)


if __name__ == "__main__":
    main()
